### ISSUE TITLE
Is this a new bug in the Pinecone Python client?

### ISSUE THREAD

**Issue by Si-za1** [pinecone-io/pinecone-python-client#286]
- [ ]  I believe this is a new bug in the Pinecone Python Client
- [ ]  I have searched the existing issues, and I could not find an existing issue for this bug

**Current Behavior**
I have Pinecone upgraded to v3.0.0 and also installed the GRPC client. 

**When I run the following command:**

`pinecone.init(api_key="API_KEY", environment="ENV")`

**I get the following error:**

`AttributeError: module 'pinecone' has no attribute 'init'`

Expected Behavior
Previously the same code was perfectly running in the Google Colab with no issue. But, today suddenly this issue arrived. 

Methods Tried:
When further researching, some searches suggested re-installing the pinecone-client, and installing the v3.0.0, but none of the solutions worked. 

Environment
```
- Google Colab:
- Python: 3.10.12
- pinecone: 3.0.0
-openai: 0.27.7 
```

**Comment by gdj0nes** [comment]
The v3 version of the client has breaking changes. Here's the [migration guide.](https://canyon-quilt-082.notion.site/Pinecone-Python-SDK-v3-0-0-Migration-Guide-056d3897d7634bf7be399676a4757c7b)

**Comment by jhamon** [comment]
Yes, the `.init()` method is no longer used in v3.0.0. Instead you should instantiate a client index like this:

```
from pinecone import Pinecone

pc = Pinecone(api_key='YOUR_API_KEY')

# Now do stuff

pc.describe_index('my_index')
```

This approach encapsulates configuration state in the class instance so that people can work with multiple pinecone projects from the same app, if they wish.

I'm going to try to add some better warning messages to help give better guidance on the necessary migration.
